# Databricks notebook source
# MAGIC %run ../00-helpers/01.enviroment-config

# COMMAND ----------

catalog_schema = f"{catalog_name}.{gold_schema}"

# Eski tabloları si

# Dimension'lar
spark.sql(f"""
CREATE TABLE IF NOT EXISTS {catalog_schema}.dim_customers (
  customer_sk BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id STRING NOT NULL,
  name        STRING,
  city        STRING,
  state       STRING,
  domains     STRING
) USING DELTA
""")

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {catalog_schema}.dim_products (
  product_sk       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  product_id       STRING NOT NULL,
  product_name     STRING,
  category         STRING,
  brand            STRING,
  price            DOUBLE,
  discounted_price DOUBLE
) USING DELTA
""")

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {catalog_schema}.dim_regions (
  region_sk BIGINT GENERATED BY DEFAULT AS IDENTITY,
  region_id STRING NOT NULL,
  region    STRING
) USING DELTA
""")

# Fact
spark.sql(f"""
CREATE TABLE IF NOT EXISTS {catalog_schema}.fact_orders (
  order_id     STRING NOT NULL,
  customer_sk  BIGINT,
  product_sk   BIGINT,
  quantity     INT,
  total_amount DOUBLE
) USING DELTA
""")

for table, sk, bk in [("dim_customers", "customer_sk", "customer_id"),
                      ("dim_products",  "product_sk",  "product_id"),
                      ("dim_regions",   "region_sk",   "region_id")]:
    spark.sql(f"""
      INSERT INTO {catalog_schema}.{table} ({sk}, {bk})
      SELECT -1, 'UNKNOWN'
      WHERE NOT EXISTS (SELECT 1 FROM {catalog_schema}.{table} WHERE {sk} = -1)
    """)
